### ISSUE TITLE
4001. Sätta upp en server [8][1]

### ISSUE THREAD

**Issue by vicper-4** [emilvidmark/d0020e#23]
Starta upp en stabil server (som kanske bara mobiler som använder appen kommer åt?)

**Comment by Synapz3** [comment]
#Servern installerad 
__MariaDB__ och __Flask__ är installerade och konfigurerat för åtkomst med __mySQL Workbench__.
Serverns ip: __130.240.207.6__
DNS: __database.sudo.pro__
SSH: _(user)___@database.sudo.pro__
