### ISSUE TITLE
5001. Simulering av positionsdata [20][5]

### ISSUE THREAD

**Issue by vicper-4** [emilvidmark/d0020e#28]
Simulering av positionsdata för testning av larmfunktion med mera

**Comment by Synapz3** [comment]
Simuleringen görs från serversidan.

X (1,2048)
Y (1,2048)
Z (1,255)

database.sudo.pro/simpos
Kräver userID

ex på användning:
$ watch -n 1 curl -w "\n" -X POST -d "userID=1" database.sudo.pro/simpos
